name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create ZIP
        run: |
          mkdir dist
          cp manifest.json dist/
          cp icon.png dist/
          cp script.js dist/
          cd dist
          zip -r ../month-total-chrome-extension-${GITHUB_REF#refs/tags/}.zip *

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: month-total-chrome-extension-${{ github.ref_name }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
